spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/flowershop'
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: NarutoAndSasukeL0ve
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  group:
    logging-layers: ru.neoflex.flowershop.service, ru.neoflex.flowershop.controller
  level:
    logging-layers: DEBUG